service: svlerssnode

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handler
    environment:
      bucket: serverlessnodejstest
    events:
      - s3:
        bucket: serverlessnodejstest
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploads/
          - suffix: .png
      - s3:
        bucket: serverlessnodejstest
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploads/
          - suffix: .jpg
